In [2]:
import os
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [3]:
# define the directory path to the Tests folder
tests_dir = "./Tests"

# create empty list to store all the dataframes for each test
df_list = []

# loop through all the folders in the Tests directory
for folder in os.listdir(tests_dir):
    
    # if the folder is not a directory, skip it
    if not os.path.isdir(os.path.join(tests_dir, folder)):
        continue
        
    # get the path to the Bilgi.txt file for the current folder
    bilgi_file = os.path.join(tests_dir, folder, "Bilgi.txt")
    
    # read in the data from the Bilgi.txt file
    with open(bilgi_file, "r") as f:
        data = f.readlines()
    
    # extract the gender, age, height, and weight from the data
    gender = data[0].strip().split(":")[1].strip()
    weight = data[1].strip().split(":")[1].strip()
    height = data[2].strip().split(":")[1].strip()
    age = data[3].strip().split(":")[1].strip()
    
    # loop through all the activity folders for the current volunteer
    for activity in os.listdir(os.path.join(tests_dir, folder, "Testler Export")):
        
        # if the activity is not a directory, skip it
        if not os.path.isdir(os.path.join(tests_dir, folder, "Testler Export", activity)):
            continue
        
        # loop through all the test folders for the current activity
        for test_folder in os.listdir(os.path.join(tests_dir, folder, "Testler Export", activity)):
            
            # if the test folder is not a directory, skip it
            if not os.path.isdir(os.path.join(tests_dir, folder, "Testler Export", activity, test_folder)):
                continue
            
            # loop through all the sensor files for the current test
            for sensor_file in os.listdir(os.path.join(tests_dir, folder, "Testler Export", activity, test_folder)):
                
                # if the file is not a txt file, skip it
                if not sensor_file.endswith(".txt"):
                    continue
                
                # get the path to the current sensor file
                sensor_path = os.path.join(tests_dir, folder, "Testler Export", activity, test_folder, sensor_file)
                
                # read in the data from the sensor file
                sensor_data = pd.read_csv(sensor_path, sep="\t",error_bad_lines=False,skiprows=5, names=["Counter","Temperature","VelInc_X",
                                                                          "VelInc_Y","VelInc_Z","OriInc_w","OriInc_x","OriInc_y",
                                                                          "OriInc_z","Acc_X","Acc_Y","Acc_Z","Gyr_X","Gyr_Y","Gyr_Z",
                                                                          "Mag_X","Mag_Y","Mag_Z","Pressure","Roll","Pitch","Yaw","RSSI"])
                
                # add columns for gender, age, height, and weight
                sensor_data["Gender"] = gender
                sensor_data["Age"] = age
                sensor_data["Height"] = height
                sensor_data["Weight"] = weight
                
                # add columns for volunteer, activity, and test number and Sensor
                sensor_data["Volunteer"] = folder
                sensor_data["Activity"] = activity
                sensor_data["Test"] = test_folder[-1]
                
                # add a column for sensor name based on the text file name
                if sensor_file == "340506.txt":
                    sensor_data["Sensor"] = "Head Sensor"
                elif sensor_file == "340527.txt":
                    sensor_data["Sensor"] = "Chest Sensor"
                elif sensor_file == "340535.txt":
                    sensor_data["Sensor"] = "Waist Sensor"
                elif sensor_file == "340537.txt":
                    sensor_data["Sensor"] = "Right Wrist Sensor"
                elif sensor_file == "340539.txt":
                    sensor_data["Sensor"] = "Right Thigh Sensor"
                elif sensor_file == "340540.txt":
                    sensor_data["Sensor"] = "Right Ankle Sensor"
                else:
                    sensor_name = sensor_file.split('.')[0]
                    sensor_data["Sensor"] = f"Unknown Sensor ({sensor_name})"
                   
                # add the sensor data for the current test to the df_list
                df_list.append(sensor_data)
                
# concatenate all the dataframes in the df_list into a
df = pd.concat(df_list, ignore_index=True)

In [4]:
df.head(10)

,Counter,Temperature,VelInc_X,VelInc_Y,VelInc_Z,OriInc_w,OriInc_x,OriInc_y,OriInc_z,Acc_X,...,Yaw,RSSI,Gender,Age,Height,Weight,Volunteer,Activity,Test,Sensor
0,0,0.001160,-0.373230,-0.121765,0.999999,0.000031,0.000516,0.000637,0.028992,-9.330750,...,-75.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
1,0,0.001115,-0.373789,-0.122840,0.999999,0.000232,0.000402,0.000549,0.027871,-9.344721,...,-75.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
2,0,0.000427,-0.373657,-0.121826,0.999999,0.000496,0.000478,0.000340,0.010681,-9.341431,...,-75.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
3,0,-0.001422,-0.374447,-0.119565,0.999999,0.000605,0.000301,0.000519,-0.035548,-9.361172,...,-76.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
4,0,-0.000427,-0.373535,-0.118042,0.999999,0.000526,0.000348,0.000519,-0.010681,-9.338379,...,-76.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
5,0,-0.003294,-0.371705,-0.118875,0.999999,0.000182,0.000259,0.000438,-0.082350,-9.292626,...,-77.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
6,0,-0.002686,-0.371155,-0.120178,0.999999,-0.000053,0.000234,0.000206,-0.067139,-9.278870,...,-78.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
7,0,-0.004126,-0.374436,-0.122784,0.999999,-0.000143,0.000153,0.000133,-0.103140,-9.360909,...,-79.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
8,0,-0.005005,-0.374817,-0.124634,0.999999,0.000572,-0.000106,0.000042,-0.125122,-9.370422,...,-79.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor
9,0,-0.001218,-0.372152,-0.124208,0.999999,0.000880,-0.000219,-0.000420,-0.030446,-9.303808,...,-79.0,NaN,Male,27,176,67,104,801-Yurume Ileri,1,Right Ankle Sensor

In [5]:
df.Sensor.unique()

array(['Right Ankle Sensor', 'Chest Sensor', 'Right Wrist Sensor',
       'Waist Sensor', 'Right Thigh Sensor', 'Head Sensor',
       'Unknown Sensor (535)', 'Unknown Sensor (340740)'], dtype=object)

In [6]:
# Filter out rows where the Sensor column contains "Unknown Sensor"
df = df[df['Sensor'].str.contains('Unknown Sensor') == False]

#### Splitting the 'Activity' column into Type and Number of the activity

In [7]:
df['Activity Type'] = df['Activity'].str[0].apply(lambda x: 'Daily activities' if x=='8' else 'Falling actions')
df['Activity Number'] = df['Activity'].str[:3]
df.drop('Activity', axis=1, inplace=True)

In [8]:
df.head(5)

,Counter,Temperature,VelInc_X,VelInc_Y,VelInc_Z,OriInc_w,OriInc_x,OriInc_y,OriInc_z,Acc_X,...,RSSI,Gender,Age,Height,Weight,Volunteer,Test,Sensor,Activity Type,Activity Number
0,0,0.001160,-0.373230,-0.121765,0.999999,0.000031,0.000516,0.000637,0.028992,-9.330750,...,NaN,Male,27,176,67,104,1,Right Ankle Sensor,Daily activities,801
1,0,0.001115,-0.373789,-0.122840,0.999999,0.000232,0.000402,0.000549,0.027871,-9.344721,...,NaN,Male,27,176,67,104,1,Right Ankle Sensor,Daily activities,801
2,0,0.000427,-0.373657,-0.121826,0.999999,0.000496,0.000478,0.000340,0.010681,-9.341431,...,NaN,Male,27,176,67,104,1,Right Ankle Sensor,Daily activities,801
3,0,-0.001422,-0.374447,-0.119565,0.999999,0.000605,0.000301,0.000519,-0.035548,-9.361172,...,NaN,Male,27,176,67,104,1,Right Ankle Sensor,Daily activities,801
4,0,-0.000427,-0.373535,-0.118042,0.999999,0.000526,0.000348,0.000519,-0.010681,-9.338379,...,NaN,Male,27,176,67,104,1,Right Ankle Sensor,Daily activities,801

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9493571 entries, 0 to 9494204
Data columns (total 32 columns):
 #   Column           Dtype
---  ------           -----
 0   Counter          object
 1   Temperature      float64
 2   VelInc_X         float64
 3   VelInc_Y         float64
 4   VelInc_Z         float64
 5   OriInc_w         float64
 6   OriInc_x         float64
 7   OriInc_y         float64
 8   OriInc_z         float64
 9   Acc_X            float64
 10  Acc_Y            float64
 11  Acc_Z            float64
 12  Gyr_X            float64
 13  Gyr_Y            float64
 14  Gyr_Z            float64
 15  Mag_X            float64
 16  Mag_Y            float64
 17  Mag_Z            float64
 18  Pressure         float64
 19  Roll             float64
 20  Pitch            float64
 21  Yaw              float64
 22  RSSI             float64
 23  Gender           object
 24  Age              object
 25  Height           object
 26  Weight           object
 27  Volunteer        object
 28  Test             object
 29  Sensor           object
 30  Activity Type    object
 31  Activity Number  object
dtypes: float64(22), object(10)
memory usage: 2.3+ GB

In [10]:
df["Activity Number"].unique()

array(['801', '814', '917', '906', '912', '804', '903', '806', '909',
       '812', '916', '805', '803', '915', '908', '907', '904', '808',
       '911', '905', '815', '810', '813', '914', '901', '919', '811',
       '913', '918', '816', '920', '807', '910', '902', '809', '802'],
      dtype=object)

In [9]:
#df["Activity Name"].replace({'1-Yurume Ileri':'walking-fw, walking forward', 
                      #  '4-YatagaOturma':'sit-bed from vertical, to sitting with a certain acceleration onto a bed (soft surface)', 
                      #   '7-YataktanDusme':'rolling-out-bed, from lying, rolling out of bed and going on the floor',
                      #  '6-OneYavasKalkma':'front-slow-recovery, from vertical falling on the floor and slow recovery', 
                      #  '2-GeriyeDogruSollu':'back-left, from vertical falling on the floor, ending lying in left lateral position', 
                      #  '4-ComelmeKalkma':'squatting-down, squatting, then standing up',
                      #  '3-OneDogruDizlerUzerine':'front-knees, from vertical falling down on the knees', 
                      #  '6-EgilmeVeAlma':'bending-pick-up, bending to pick up an object on the floor', 
                      #  '9-GeriyeDogruOturma':'back-sitting, from vertical falling on the floor, ending sitting',
                      #  '2-Kanepe':'sit-sofa from vertical, to sitting with a certain acceleration onto a sofa (soft surface)', 
                      #  '6-YanaSolluCabukKalkma':'left-recovery, from vertical falling on the floor with subsequent recovery', 
                      #  '5-Egilme':'bending, bending about 90 degrees',
                      #  '3-TempoluYavasKosu':'jogging, running', 
                      #  '5-YanaSollu':'left-sideway, from vertical falling on the floor, ending lying', 
                      #  '8-OneDogruSollu':'front-left, from vertical falling down on the floor, ending in left lateral position',
                      #  '7-OneDogruSagli':'front-right, from vertical falling down on the floor, ending in right lateral position',
                      #  '4-OneDogruDizlerUzerineArdindanUzanma':'front-knees-lying, from vertical falling down on the knees and then lying on the floor',
                      #  '8-Tokezleme':'stumble, stumbling with recovery',
                      #  '1-GeriyeDogruSagli':'back-right, from vertical falling on the floor, ending lying in right lateral position',
                      #  '5-OneCabukKalkma':'front-quick-recovery, from vertical falling on the floor and quick recovery',
                      #  '5-YatagaUzanma':'lying-bed, from vertical lying on the bed', 
                      #  '0-Oksurme':'oughing-sneezing, coughing or sneezing', 
                      #  '3-HavayaOturma':'sit-air from vertical, to sitting in the air exploiting the muscles of legs',
                      #  '4-YanaSagliCabukKalkma':'right-recovery, from vertical falling on the floor with subsequent recovery', 
                      #  '1-OneDogruUzanma':'front-lying, from vertical falling forward to the floor', 
                      #  '9-Bayilma':'syncope, from standing falling on the floor following a vertical trajectory',
                      #  '1-Sandalye':'sit-chair from vertical, to sitting with a certain acceleration onto a chair (hard surface)',
                      #  '3-YanaSagli':'right-sideway, from vertical falling on the floor, ending lying', 
                      #  '8-Podyum':'podium, from vertical standing on a podium going on the floor', 
                      #  '6-YataktanKalkma':'rising-bed, from lying to sitting',
                      #  '0-BayilmaDuvar':'syncope-wall, from standing falling down slowly slipping on a wall', 
                      #  '7-Topallama':'limp, walking with a limp', 
                      #  '0-GeriyeDogruUzanma':'back-lying, from vertical falling on the floor, ending lying',
                      #  '2-OneDogruKorunarakDusme':'front-protecting-lying, from vertical falling forward to the floor with arm protection', 
                      #  '9-AyakBurkulmasi':'trip-over, bending while walking and then continuing walking', 
                      #  '2-YurumeGeri':'walking-bw, walking backward',
                      #  '7-Topallam':'limp, walking with a limp'},inplace=True)

In [10]:
#df['Activity'].replace({'801-Yurume Ileri':'walking-fw', '814-YatagaOturma':'sit-bed from vertical', '917-YataktanDusme',
      # '906-OneYavasKalkma', '912-GeriyeDogruSollu', '804-ComelmeKalkma',
      # '903-OneDogruDizlerUzerine', '806-EgilmeVeAlma',
      # '909-GeriyeDogruOturma', '812-Kanepe', '916-YanaSolluCabukKalkma',
      # '805-Egilme', '803-TempoluYavasKosu', '915-YanaSollu',
       #'908-OneDogruSollu', '907-OneDogruSagli',
      # '904-OneDogruDizlerUzerineArdindanUzanma', '808-Tokezleme',
      # '911-GeriyeDogruSagli', '905-OneCabukKalkma', '815-YatagaUzanma',
      # '810-Oksurme', '813-HavayaOturma', '914-YanaSagliCabukKalkma',
      # '901-OneDogruUzanma', '919-Bayilma', '811-Sandalye',
      # '913-YanaSagli', '918-Podyum', '816-YataktanKalkma',
      # '920-BayilmaDuvar', '807-Topallama', '910-GeriyeDogruUzanma',
     #  '902-OneDogruKorunarakDusme', '809-AyakBurkulmasi',
      # '802-YurumeGeri', '807-Topallam'})

In [11]:
df.shape

(9493571, 32)

In [12]:
df.to_csv('FallSimulation.csv', index=False)