In [1]:
%matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import timeit as ti
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
ven=pd.read_csv('./data/Restaurant/vendors.csv')
odr=pd.read_csv('./data/Restaurant/orders.csv')
cust=pd.read_csv('./data/Restaurant/train_customers.csv')
loc=pd.read_csv('./data/Restaurant/train_locations.csv')

VENDOR DATASET

In [3]:
ven

,id,authentication_id,latitude,longitude,vendor_category_en,vendor_category_id,delivery_charge,serving_distance,is_open,OpeningTime,...,open_close_flags,vendor_tag,vendor_tag_name,one_click_vendor,country_id,city_id,created_at,updated_at,device_type,display_orders
0,4,118597.0,-0.588596,0.754434,Restaurants,2.0,0.0,6.0,1.0,11:00AM-11:30PM,...,1.0,"2,4,5,8,91,22,12,24,16,23","Arabic,Breakfast,Burgers,Desserts,Free Deliver...",Y,1.0,1.0,2018-01-30 14:42:04,2020-04-07 15:12:43,3,1
1,13,118608.0,-0.471654,0.744470,Restaurants,2.0,0.7,5.0,1.0,08:30AM-10:30PM,...,1.0,"4,41,51,34,27,15,24,16,28","Breakfast,Cakes,Crepes,Italian,Pasta,Pizzas,Sa...",Y,1.0,1.0,2018-05-03 12:32:06,2020-04-05 20:46:03,3,1
2,20,118616.0,-0.407527,0.643681,Restaurants,2.0,0.0,8.0,1.0,08:00AM-10:45PM,...,1.0,"4,8,91,10","Breakfast,Desserts,Free Delivery,Indian",Y,1.0,1.0,2018-05-04 22:28:22,2020-04-07 16:35:55,3,1
3,23,118619.0,-0.585385,0.753811,Restaurants,2.0,0.0,5.0,1.0,10:59AM-10:30PM,...,1.0,"5,8,30,24","Burgers,Desserts,Fries,Salads",Y,1.0,1.0,2018-05-06 19:20:48,2020-04-02 00:56:17,3,1
4,28,118624.0,0.480602,0.552850,Restaurants,2.0,0.7,15.0,1.0,11:00AM-11:45PM,...,1.0,5,Burgers,Y,1.0,1.0,2018-05-17 22:12:38,2020-04-05 15:57:41,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,849,130455.0,-1.588060,-0.066441,Restaurants,2.0,0.0,10.0,1.0,NaN,...,1.0,"1,4,5,6,8,91,30,43,48,24","American,Breakfast,Burgers,Cafe,Desserts,Free ...",Y,1.0,1.0,2019-12-21 12:47:39,2020-04-07 20:01:33,3,1
96,855,130463.0,2.145206,0.745025,Restaurants,2.0,0.0,8.0,1.0,NaN,...,1.0,"1,5,8,91,30,48,24","American,Burgers,Desserts,Free Delivery,Fries,...",Y,1.0,1.0,2019-12-21 13:02:32,2020-04-07 01:50:41,3,1
97,856,130464.0,0.251469,0.483632,Restaurants,2.0,0.0,7.0,1.0,NaN,...,1.0,"1,4,5,6,8,91,30,43,48,24","American,Breakfast,Burgers,Cafe,Desserts,Free ...",Y,1.0,1.0,2019-12-21 13:04:34,2020-04-06 23:53:16,3,1
98,858,130468.0,0.019817,0.587087,Restaurants,2.0,0.0,3.0,1.0,NaN,...,1.0,"1,4,5,6,8,91,30,43,48,24","American,Breakfast,Burgers,Cafe,Desserts,Free ...",Y,1.0,1.0,2019-12-21 13:12:09,2020-04-07 14:26:08,3,1
99,907,132953.0,13.335131,-1.449556,Restaurants,2.0,0.7,12.0,1.0,NaN,...,1.0,"46,52,16","Fatayers,Mojitos ,Sandwiches",Y,1.0,1.0,2020-01-05 18:56:58,2020-04-06 23:49:52,3,1

In [4]:
ven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 59 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    100 non-null    int64
 1   authentication_id     100 non-null    float64
 2   latitude              100 non-null    float64
 3   longitude             100 non-null    float64
 4   vendor_category_en    100 non-null    object
 5   vendor_category_id    100 non-null    float64
 6   delivery_charge       100 non-null    float64
 7   serving_distance      100 non-null    float64
 8   is_open               100 non-null    float64
 9   OpeningTime           91 non-null     object
 10  OpeningTime2          91 non-null     object
 11  prepration_time       100 non-null    int64
 12  commission            85 non-null     float64
 13  is_akeed_delivering   100 non-null    object
 14  discount_percentage   100 non-null    float64
 15  status                100 non-null    float64
 16  verified              100 non-null    int64
 17  rank                  100 non-null    int64
 18  language              85 non-null     object
 19  vendor_rating         100 non-null    float64
 20  sunday_from_time1     99 non-null     object
 21  sunday_to_time1       99 non-null     object
 22  sunday_from_time2     42 non-null     object
 23  sunday_to_time2       42 non-null     object
 24  monday_from_time1     100 non-null    object
 25  monday_to_time1       100 non-null    object
 26  monday_from_time2     42 non-null     object
 27  monday_to_time2       42 non-null     object
 28  tuesday_from_time1    99 non-null     object
 29  tuesday_to_time1      99 non-null     object
 30  tuesday_from_time2    41 non-null     object
 31  tuesday_to_time2      41 non-null     object
 32  wednesday_from_time1  100 non-null    object
 33  wednesday_to_time1    100 non-null    object
 34  wednesday_from_time2  42 non-null     object
 35  wednesday_to_time2    42 non-null     object
 36  thursday_from_time1   99 non-null     object
 37  thursday_to_time1     99 non-null     object
 38  thursday_from_time2   42 non-null     object
 39  thursday_to_time2     42 non-null     object
 40  friday_from_time1     96 non-null     object
 41  friday_to_time1       96 non-null     object
 42  friday_from_time2     45 non-null     object
 43  friday_to_time2       45 non-null     object
 44  saturday_from_time1   98 non-null     object
 45  saturday_to_time1     98 non-null     object
 46  saturday_from_time2   42 non-null     object
 47  saturday_to_time2     42 non-null     object
 48  primary_tags          77 non-null     object
 49  open_close_flags      100 non-null    float64
 50  vendor_tag            97 non-null     object
 51  vendor_tag_name       97 non-null     object
 52  one_click_vendor      100 non-null    object
 53  country_id            100 non-null    float64
 54  city_id               100 non-null    float64
 55  created_at            100 non-null    object
 56  updated_at            100 non-null    object
 57  device_type           100 non-null    int64
 58  display_orders        100 non-null    int64
dtypes: float64(14), int64(6), object(39)
memory usage: 46.2+ KB

In [5]:
ven.describe()

,id,authentication_id,latitude,longitude,vendor_category_id,delivery_charge,serving_distance,is_open,prepration_time,commission,discount_percentage,status,verified,rank,vendor_rating,open_close_flags,country_id,city_id,device_type,display_orders
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.00000,85.0,100.000000,100.00000,100.000000,100.00000,100.000000,100.0,100.0,100.0,100.00,100.0
mean,288.840000,120050.760000,1.875505,0.803682,2.110000,0.413000,11.750000,0.85000,14.03000,0.0,1.100000,0.85000,0.880000,9.90000,4.350000,1.0,1.0,1.0,2.98,1.0
std,242.299994,3509.069064,20.600857,4.397859,0.314466,0.346018,4.108073,0.35887,4.31688,0.0,6.299751,0.35887,0.326599,3.14466,0.248836,0.0,0.0,0.0,0.20,0.0
min,4.000000,118597.000000,-1.787413,-1.449556,2.000000,0.000000,2.000000,0.00000,5.00000,0.0,0.000000,0.00000,0.000000,1.00000,3.200000,1.0,1.0,1.0,1.00,1.0
25%,105.750000,118702.750000,-0.809124,0.081618,2.000000,0.000000,8.000000,1.00000,10.00000,0.0,0.000000,1.00000,1.000000,11.00000,4.200000,1.0,1.0,1.0,3.00,1.0
50%,202.000000,118801.000000,-0.493421,0.527123,2.000000,0.700000,15.000000,1.00000,15.00000,0.0,0.000000,1.00000,1.000000,11.00000,4.400000,1.0,1.0,1.0,3.00,1.0
75%,387.250000,118990.250000,0.015915,0.644764,2.000000,0.700000,15.000000,1.00000,15.00000,0.0,0.000000,1.00000,1.000000,11.00000,4.500000,1.0,1.0,1.0,3.00,1.0
max,907.000000,132953.000000,205.242327,44.210807,3.000000,0.700000,15.000000,1.00000,45.00000,0.0,50.000000,1.00000,1.000000,11.00000,4.800000,1.0,1.0,1.0,3.00,1.0

Removing insignificant columns

In [6]:
ven.drop(['language','display_orders','device_type','city_id',
         'country_id','open_close_flags','commission','is_akeed_delivering',
         'one_click_vendor','OpeningTime','OpeningTime2','vendor_tag',
          'tuesday_from_time1','tuesday_to_time1','tuesday_from_time2','tuesday_to_time2',
         'wednesday_from_time1','wednesday_to_time1','wednesday_from_time2','wednesday_to_time2',
         'thursday_from_time1','thursday_to_time1','thursday_from_time2','thursday_to_time2',
         'friday_from_time1','friday_to_time1','friday_from_time2','friday_to_time2',
         'saturday_from_time1','saturday_to_time1','saturday_from_time2','saturday_to_time2',
          'sunday_from_time1','sunday_to_time1','sunday_from_time2','sunday_to_time2',
          'monday_from_time1','monday_to_time1','monday_from_time2','monday_to_time2'],axis=1,inplace=True)

In [7]:
ven=ven.rename(columns={'id':'vendor_id'})

In [8]:
ven.head()

,vendor_id,authentication_id,latitude,longitude,vendor_category_en,vendor_category_id,delivery_charge,serving_distance,is_open,prepration_time,discount_percentage,status,verified,rank,vendor_rating,primary_tags,vendor_tag_name,created_at,updated_at
0,4,118597.0,-0.588596,0.754434,Restaurants,2.0,0.0,6.0,1.0,15,0.0,1.0,1,11,4.4,"{""primary_tags"":""4""}","Arabic,Breakfast,Burgers,Desserts,Free Deliver...",2018-01-30 14:42:04,2020-04-07 15:12:43
1,13,118608.0,-0.471654,0.744470,Restaurants,2.0,0.7,5.0,1.0,14,0.0,1.0,1,11,4.7,"{""primary_tags"":""7""}","Breakfast,Cakes,Crepes,Italian,Pasta,Pizzas,Sa...",2018-05-03 12:32:06,2020-04-05 20:46:03
2,20,118616.0,-0.407527,0.643681,Restaurants,2.0,0.0,8.0,1.0,19,0.0,1.0,1,1,4.5,"{""primary_tags"":""71""}","Breakfast,Desserts,Free Delivery,Indian",2018-05-04 22:28:22,2020-04-07 16:35:55
3,23,118619.0,-0.585385,0.753811,Restaurants,2.0,0.0,5.0,1.0,16,0.0,1.0,1,11,4.5,"{""primary_tags"":""46""}","Burgers,Desserts,Fries,Salads",2018-05-06 19:20:48,2020-04-02 00:56:17
4,28,118624.0,0.480602,0.552850,Restaurants,2.0,0.7,15.0,1.0,10,0.0,1.0,1,11,4.4,"{""primary_tags"":""32""}",Burgers,2018-05-17 22:12:38,2020-04-05 15:57:41

Checking for NaN values in the dataset in each column.

In [9]:
ven.isna().sum()

vendor_id               0
authentication_id       0
latitude                0
longitude               0
vendor_category_en      0
vendor_category_id      0
delivery_charge         0
serving_distance        0
is_open                 0
prepration_time         0
discount_percentage     0
status                  0
verified                0
rank                    0
vendor_rating           0
primary_tags           23
vendor_tag_name         3
created_at              0
updated_at              0
dtype: int64

Filling NaN spaces for the weekend and weekday columns

In [10]:
def tsort(x):
    a=x.split(":")[1]
    return int(a.split('"')[1])
ven['primary_tags'].fillna('{"primary_tags":"0"}',inplace=True)
ven['primary_tags']=ven['primary_tags'].apply(tsort)

In [11]:
ven=ven.dropna(axis=0, how='any', subset='vendor_tag_name')

In [12]:
ven.shape

(97, 19)

In [13]:
ven.isnull().values.any()

False

ORDER DATASET

In [14]:
odr.head(5)

,akeed_order_id,customer_id,item_count,grand_total,payment_mode,promo_code,vendor_discount_amount,promo_code_discount_percentage,is_favorite,is_rated,...,driver_accepted_time,ready_for_pickup_time,picked_up_time,delivered_time,delivery_date,vendor_id,created_at,LOCATION_NUMBER,LOCATION_TYPE,CID X LOC_NUM X VENDOR
0,163238.0,92PEE24,1.0,7.6,2,NaN,0.0,NaN,NaN,No,...,NaN,NaN,NaN,NaN,2019-07-31 05:30:00,105,2019-08-01 05:30:16,0,NaN,92PEE24 X 0 X 105
1,163240.0,QS68UD8,1.0,8.7,1,NaN,0.0,NaN,NaN,No,...,NaN,NaN,NaN,NaN,2019-07-31 05:30:00,294,2019-08-01 05:31:10,0,Work,QS68UD8 X 0 X 294
2,163241.0,MB7VY5F,2.0,14.4,1,NaN,0.0,NaN,NaN,No,...,NaN,NaN,NaN,NaN,2019-07-31 05:30:00,83,2019-08-01 05:31:33,0,NaN,MB7VY5F X 0 X 83
3,163244.0,KDJ951Y,1.0,7.1,1,NaN,0.0,NaN,NaN,No,...,NaN,NaN,NaN,NaN,2019-07-31 05:30:00,90,2019-08-01 05:34:54,0,Home,KDJ951Y X 0 X 90
4,163245.0,BAL0RVT,4.0,27.2,1,NaN,0.0,NaN,NaN,No,...,NaN,NaN,NaN,NaN,2019-07-31 05:30:00,83,2019-08-01 05:35:51,0,Work,BAL0RVT X 0 X 83

In [15]:
odr.describe()

,akeed_order_id,item_count,grand_total,payment_mode,vendor_discount_amount,promo_code_discount_percentage,vendor_rating,driver_rating,deliverydistance,preparationtime,vendor_id,LOCATION_NUMBER
count,135233.000000,128378.000000,135303.000000,135303.000000,135303.000000,65880.000000,45220.000000,135303.000000,135303.000000,79743.000000,135303.000000,135303.000000
mean,265190.206155,2.405404,15.374513,1.345159,0.001053,0.026639,1.959730,0.675366,4.104255,43.181721,239.214866,0.867527
std,85051.488939,1.645332,12.556177,0.763712,0.047331,0.813320,2.313294,1.667261,4.361884,7.107582,226.437406,1.239884
min,11044.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,25.000000,4.000000,0.000000
25%,190852.000000,1.000000,8.200000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,40.000000,84.000000,0.000000
50%,267166.000000,2.000000,11.700000,1.000000,0.000000,0.000000,0.000000,0.000000,2.900000,45.000000,157.000000,0.000000
75%,336230.000000,3.000000,18.500000,1.000000,0.000000,0.000000,5.000000,0.000000,7.920000,45.000000,299.000000,1.000000
max,415515.000000,68.000000,783.800000,5.000000,10.650000,25.000000,5.000000,5.000000,19.810000,90.000000,907.000000,25.000000

In [16]:
odr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   akeed_order_id                  135233 non-null  float64
 1   customer_id                     135303 non-null  object
 2   item_count                      128378 non-null  float64
 3   grand_total                     135303 non-null  float64
 4   payment_mode                    135303 non-null  int64
 5   promo_code                      4305 non-null    object
 6   vendor_discount_amount          135303 non-null  float64
 7   promo_code_discount_percentage  65880 non-null   float64
 8   is_favorite                     100108 non-null  object
 9   is_rated                        135303 non-null  object
 10  vendor_rating                   45220 non-null   float64
 11  driver_rating                   135303 non-null  float64
 12  deliverydistance                135303 non-null  float64
 13  preparationtime                 79743 non-null   float64
 14  delivery_time                   5123 non-null    object
 15  order_accepted_time             86955 non-null   object
 16  driver_accepted_time            46458 non-null   object
 17  ready_for_pickup_time           84249 non-null   object
 18  picked_up_time                  83865 non-null   object
 19  delivered_time                  85741 non-null   object
 20  delivery_date                   35544 non-null   object
 21  vendor_id                       135303 non-null  int64
 22  created_at                      135303 non-null  object
 23  LOCATION_NUMBER                 135303 non-null  int64
 24  LOCATION_TYPE                   86410 non-null   object
 25  CID X LOC_NUM X VENDOR          135303 non-null  object
dtypes: float64(9), int64(3), object(14)
memory usage: 26.8+ MB

In [17]:
odr.isnull().sum()

akeed_order_id                        70
customer_id                            0
item_count                          6925
grand_total                            0
payment_mode                           0
promo_code                        130998
vendor_discount_amount                 0
promo_code_discount_percentage     69423
is_favorite                        35195
is_rated                               0
vendor_rating                      90083
driver_rating                          0
deliverydistance                       0
preparationtime                    55560
delivery_time                     130180
order_accepted_time                48348
driver_accepted_time               88845
ready_for_pickup_time              51054
picked_up_time                     51438
delivered_time                     49562
delivery_date                      99759
vendor_id                              0
created_at                             0
LOCATION_NUMBER                        0
LOCATION_TYPE                      48893
CID X LOC_NUM X VENDOR                 0
dtype: int64

In [18]:
odr.drop(['order_accepted_time', 'driver_accepted_time','ready_for_pickup_time', 
          'picked_up_time', 'delivered_time'],axis=1,inplace=True)

In [19]:
odr=odr.dropna(axis=0, how='any', subset='akeed_order_id')

In [20]:
odr.item_count.fillna(odr.item_count.median(),inplace=True)

In [21]:
odr.promo_code_discount_percentage.fillna(0,inplace=True)

In [22]:
odr.is_favorite.fillna('No', inplace=True)

In [23]:
i=odr.index[odr.loc[:,'vendor_rating'] == 0]
odr.drop(i,inplace=True)

In [24]:
odr=odr.dropna(axis=0, how='any', subset='vendor_rating')

In [25]:
odr['promo_code'].fillna(0,inplace=True)

In [26]:
d=odr['promo_code']
o=[]
for i in range(len(d)):
    if d.values[i]!=0:
        o.append(d.index[i])
odr['promo_code'][o]=1

In [27]:
odr.preparationtime.fillna(odr.preparationtime.mean(),inplace=True)

In [28]:
odr.dropna(axis=0, how='any', subset='LOCATION_TYPE', inplace=True)

In [29]:
odr.drop(['delivery_date'], axis=1, inplace=True)

In [30]:
odr.drop(['delivery_time'], axis=1, inplace=True)

In [31]:
odr.isnull().values.any()

False

In [32]:
odr.shape

(13280, 19)

CUSTOMER DATASET

In [33]:
cust

,akeed_customer_id,gender,dob,status,verified,language,created_at,updated_at
0,TCHWPBT,Male,NaN,1,1,EN,2018-02-07 19:16:23,2018-02-07 19:16:23
1,ZGFSYCZ,Male,NaN,1,1,EN,2018-02-09 12:04:42,2018-02-09 12:04:41
2,S2ALZFL,Male,NaN,0,1,EN,2018-03-14 18:31:43,2018-03-14 18:31:42
3,952DBJQ,Male,NaN,1,1,EN,2018-03-15 19:47:07,2018-03-15 19:47:07
4,1IX6FXS,Male,NaN,1,1,EN,2018-03-15 19:57:01,2018-03-15 19:57:01
...,...,...,...,...,...,...,...,...
34669,JAI79PE,NaN,NaN,1,1,NaN,2020-03-03 13:01:13,2020-03-03 13:02:21
34670,TR75VFL,NaN,NaN,1,1,NaN,2020-03-03 13:22:35,2020-03-03 13:22:41
34671,SQMJ08H,NaN,NaN,1,1,NaN,2020-03-03 13:24:27,2020-03-03 13:24:44
34672,9LW9CHN,NaN,NaN,1,1,NaN,2020-03-03 13:24:28,2020-03-03 13:28:00
34673,LBMRK7A,NaN,NaN,1,1,NaN,2020-03-03 13:31:52,2020-03-03 13:32:09

In [34]:
cust.describe()

               dob        status      verified
count  3046.000000  34674.000000  34674.000000
mean   1991.210768      0.998991      0.956538
std      48.422045      0.031756      0.203898
min       1.000000      0.000000      0.000000
25%    1986.000000      1.000000      1.000000
50%    1993.000000      1.000000      1.000000
75%    1999.000000      1.000000      1.000000
max    2562.000000      1.000000      1.000000

In [35]:
cust.isna().sum()

akeed_customer_id        0
gender               12154
dob                  31628
status                   0
verified                 0
language             13575
created_at               0
updated_at               0
dtype: int64

In [36]:
cust.gender.fillna('notgiven', inplace=True)

In [37]:
cust.drop('language',axis=1,inplace=True)

In [38]:
cust.drop('created_at',axis=1,inplace=True)

In [39]:
cust.drop('dob', axis=1, inplace=True)

In [40]:
cust.isnull().values.any()

False

In [41]:
cust=cust.rename(columns={'akeed_customer_id':'customer_id'})

In [42]:
cust['status'][cust['status']==0].count()

35

In [43]:
i=cust.index[ cust.loc[:,'status'] == 0]
cust.drop(i,inplace=True)
cust.drop('status',axis=1,inplace=True)

LOCATION DATASET

In [44]:
loc

      customer_id  location_number location_type  latitude  longitude
0         02SFNJH                0           NaN  1.682392 -78.789737
1         02SFNJH                1           NaN  1.679137   0.766823
2         02SFNJH                2           NaN -0.498648   0.661241
3         RU43CXC                0          Home  0.100853   0.438165
4         BDFBPRD                0           NaN  2.523125   0.733464
...           ...              ...           ...       ...        ...
59498     9PP42SA                2           NaN -0.788515 -78.497721
59499     9PP42SA                3          Home -1.445114   0.072558
59500     9PP42SA                4           NaN -0.001785   0.431695
59501     HWELAU8                0           NaN -0.066291 -78.583075
59502     HWELAU8                1           NaN -0.067043   0.648221

[59503 rows x 5 columns]

In [45]:
loc.describe()

       location_number      latitude     longitude
count     59503.000000  59497.000000  59497.000000
mean          0.753592      2.361135    -25.115410
std           1.355645     22.734109     36.946014
min           0.000000  -1038.149292   -134.415302
25%           0.000000     -0.502593    -78.522567
50%           0.000000     -0.087860      0.021342
75%           1.000000      0.261727      0.514671
max          29.000000    453.653846     45.354231

In [46]:
loc.isnull().sum()

customer_id            0
location_number        0
location_type      27209
latitude               6
longitude              6
dtype: int64

In [47]:
loc.location_type.fillna('other', inplace=True)

In [48]:
loc.dropna(inplace=True)

Merging cust and loc datasets to form con dataset.

In [49]:
con=pd.merge(cust,loc, on ='customer_id')

In [50]:
con.isnull().values.any()

False

In [51]:
con

,customer_id,gender,verified,updated_at,location_number,location_type,latitude,longitude
0,TCHWPBT,Male,1,2018-02-07 19:16:23,0,Work,-96.407538,-67.197291
1,TCHWPBT,Male,1,2018-02-07 19:16:23,1,Home,-96.645619,-67.169154
2,TCHWPBT,Male,1,2018-02-07 19:16:23,2,other,-0.128673,-78.575702
3,ZGFSYCZ,Male,1,2018-02-09 12:04:41,0,Home,-0.175558,-78.570161
4,ZGFSYCZ,Male,1,2018-02-09 12:04:41,1,Home,0.191105,-78.613494
...,...,...,...,...,...,...,...,...
58141,JAI79PE,notgiven,1,2020-03-03 13:02:21,0,other,0.166787,0.044431
58142,TR75VFL,notgiven,1,2020-03-03 13:22:41,0,other,0.091428,0.456065
58143,SQMJ08H,notgiven,1,2020-03-03 13:24:44,0,other,-0.339592,0.200884
58144,9LW9CHN,notgiven,1,2020-03-03 13:28:00,0,other,0.452519,0.009800
58145,LBMRK7A,notgiven,1,2020-03-03 13:32:09,0,Other,19.826320,3.029901

Removing the extra lower case redundant data from gender and location_type

In [52]:
def gender(x):
    try:
        x1=x.split(" ")[0]
        x1=x1.lower()
        return x1
    except:
        return np.nan
con.gender=con.gender.apply(gender)

In [53]:
def loc(x):
    try:
        x1=x.split(" ")[0]
        x1=x1.lower()
        return x1
    except:
        return np.nan
con.location_type=con.location_type.apply(loc)

Merging con and odr datasets to create the final dataset.

In [54]:
df=pd.merge(con,odr,on='customer_id')
df_final=pd.merge(df,ven, on='vendor_id')

Converting prep_time to integer.

In [55]:
prep_time=[]
def convert(x):
    global prep_time
    if x not in prep_time:
        prep_time.append(x)
    return prep_time.index(x)
df_final['prepration_time']=df_final['prepration_time'].apply(convert)

In [56]:
df_final.isnull().values.any()

False

Description of the final dataset.

In [57]:
df_final.describe()

,verified_x,location_number,latitude_x,longitude_x,akeed_order_id,item_count,grand_total,payment_mode,vendor_discount_amount,promo_code_discount_percentage,...,delivery_charge,serving_distance,is_open,prepration_time,discount_percentage,status,verified_y,rank,vendor_rating_y,primary_tags
count,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,...,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000,38027.000000
mean,0.988166,1.713546,-0.213197,-25.704088,314256.551398,2.329371,15.409927,1.425487,0.000553,0.009335,...,0.315807,12.006416,0.944408,4.391248,0.586162,0.944408,0.946538,9.955479,4.438538,470.391827
std,0.108139,2.177066,22.738061,37.297570,48944.778966,1.606602,12.832933,0.849533,0.026186,0.470608,...,0.348330,4.098112,0.229135,3.592358,4.357060,0.229135,0.224956,3.058502,0.208609,686.689312
min,0.000000,0.000000,-671.738872,-132.204545,124473.000000,1.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.200000,0.000000
25%,1.000000,0.000000,-0.433422,-78.540109,279709.000000,1.000000,8.300000,1.000000,0.000000,0.000000,...,0.000000,8.000000,1.000000,0.000000,0.000000,1.000000,1.000000,11.000000,4.300000,32.000000
50%,1.000000,1.000000,-0.080548,0.044875,307422.000000,2.000000,11.700000,1.000000,0.000000,0.000000,...,0.000000,15.000000,1.000000,6.000000,0.000000,1.000000,1.000000,11.000000,4.500000,134.000000
75%,1.000000,2.000000,0.184241,0.537358,349095.000000,3.000000,17.900000,2.000000,0.000000,0.000000,...,0.700000,15.000000,1.000000,6.000000,0.000000,1.000000,1.000000,11.000000,4.600000,478.000000
max,1.000000,29.000000,453.653846,45.354231,415508.000000,28.000000,177.400000,5.000000,3.050000,25.000000,...,0.700000,15.000000,1.000000,13.000000,50.000000,1.000000,1.000000,11.000000,4.800000,2396.000000

In [58]:
df_final

,customer_id,gender,verified_x,updated_at_x,location_number,location_type,latitude_x,longitude_x,akeed_order_id,item_count,...,prepration_time,discount_percentage,status,verified_y,rank,vendor_rating_y,primary_tags,vendor_tag_name,created_at_y,updated_at_y
0,ZGFSYCZ,male,1,2018-02-09 12:04:41,0,home,-0.175558,-78.570161,272483.0,1.0,...,0,0.0,1.0,1,11,4.2,134,"Fresh Juices,Sandwiches,Shawarma",2019-10-21 14:36:50,2020-04-06 23:12:29
1,ZGFSYCZ,male,1,2018-02-09 12:04:41,0,home,-0.175558,-78.570161,299088.0,1.0,...,0,0.0,1.0,1,11,4.2,134,"Fresh Juices,Sandwiches,Shawarma",2019-10-21 14:36:50,2020-04-06 23:12:29
2,ZGFSYCZ,male,1,2018-02-09 12:04:41,0,home,-0.175558,-78.570161,306616.0,1.0,...,0,0.0,1.0,1,11,4.2,134,"Fresh Juices,Sandwiches,Shawarma",2019-10-21 14:36:50,2020-04-06 23:12:29
3,ZGFSYCZ,male,1,2018-02-09 12:04:41,0,home,-0.175558,-78.570161,324400.0,2.0,...,0,0.0,1.0,1,11,4.2,134,"Fresh Juices,Sandwiches,Shawarma",2019-10-21 14:36:50,2020-04-06 23:12:29
4,ZGFSYCZ,male,1,2018-02-09 12:04:41,0,home,-0.175558,-78.570161,364843.0,4.0,...,0,0.0,1.0,1,11,4.2,134,"Fresh Juices,Sandwiches,Shawarma",2019-10-21 14:36:50,2020-04-06 23:12:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38022,ARQI65D,notgiven,1,2020-02-13 21:45:11,0,home,13.419926,-1.335253,387613.0,4.0,...,13,0.0,1.0,1,11,4.3,24,"Fatayers,Mojitos ,Sandwiches",2020-01-05 18:56:58,2020-04-06 23:49:52
38023,FDT09GH,notgiven,1,2020-02-14 22:36:08,0,home,13.838020,-1.409045,393551.0,3.0,...,13,0.0,1.0,1,11,4.3,24,"Fatayers,Mojitos ,Sandwiches",2020-01-05 18:56:58,2020-04-06 23:49:52
38024,RWMGT94,notgiven,0,2020-02-17 20:38:03,0,other,12.716874,-1.475248,397261.0,3.0,...,13,0.0,1.0,1,11,4.3,24,"Fatayers,Mojitos ,Sandwiches",2020-01-05 18:56:58,2020-04-06 23:49:52
38025,33FVV46,notgiven,1,2020-02-24 19:20:45,0,home,12.905977,-1.454105,398748.0,3.0,...,13,0.0,1.0,1,11,4.3,24,"Fatayers,Mojitos ,Sandwiches",2020-01-05 18:56:58,2020-04-06 23:49:52
38026,3B63I7F,notgiven,1,2020-02-24 23:07:21,0,home,14.216782,-1.466578,399359.0,5.0,...,13,0.0,1.0,1,11,4.3,24,"Fatayers,Mojitos ,Sandwiches",2020-01-05 18:56:58,2020-04-06 23:49:52

In [64]:
df_final.dtypes

customer_id                         int64
gender                             object
verified_x                          int64
updated_at_x                       object
location_number                     int64
location_type                      object
latitude_x                        float64
longitude_x                       float64
akeed_order_id                    float64
item_count                        float64
grand_total                       float64
payment_mode                        int64
promo_code                         object
vendor_discount_amount            float64
promo_code_discount_percentage    float64
is_favorite                        object
is_rated                           object
vendor_rating_x                   float64
driver_rating                     float64
deliverydistance                  float64
preparationtime                   float64
vendor_id                           int64
created_at_x                       object
LOCATION_NUMBER                     int64
LOCATION_TYPE                      object
CID X LOC_NUM X VENDOR             object
authentication_id                 float64
latitude_y                        float64
longitude_y                       float64
vendor_category_en                 object
vendor_category_id                float64
delivery_charge                   float64
serving_distance                  float64
is_open                           float64
prepration_time                     int64
discount_percentage               float64
status                            float64
verified_y                          int64
rank                                int64
vendor_rating_y                   float64
primary_tags                        int64
vendor_tag_name                    object
created_at_y                       object
updated_at_y                       object
dtype: object

In [59]:
df_final.columns

Index(['customer_id', 'gender', 'verified_x', 'updated_at_x',
       'location_number', 'location_type', 'latitude_x', 'longitude_x',
       'akeed_order_id', 'item_count', 'grand_total', 'payment_mode',
       'promo_code', 'vendor_discount_amount',
       'promo_code_discount_percentage', 'is_favorite', 'is_rated',
       'vendor_rating_x', 'driver_rating', 'deliverydistance',
       'preparationtime', 'vendor_id', 'created_at_x', 'LOCATION_NUMBER',
       'LOCATION_TYPE', 'CID X LOC_NUM X VENDOR', 'authentication_id',
       'latitude_y', 'longitude_y', 'vendor_category_en', 'vendor_category_id',
       'delivery_charge', 'serving_distance', 'is_open', 'prepration_time',
       'discount_percentage', 'status', 'verified_y', 'rank',
       'vendor_rating_y', 'primary_tags', 'vendor_tag_name', 'created_at_y',
       'updated_at_y'],
      dtype='object')

Exporting final dataset.

In [60]:
df_final.to_csv('./data/Restaurant/df_final_dataset.csv')

In [61]:
cust_id=[]
def convert(x):
    global cust_id
    if x not in cust_id:
        cust_id.append(x)
    return cust_id.index(x)
df_final.customer_id=df_final.customer_id.apply(convert)

Dropping unwanted columns for the predictive analysis and exporting the new resulting dataset. (Commenting so the dataset is not created again.)

In [62]:
#df_final.drop(['verified_x', 'updated_at_x',
      # 'location_number', 'location_type', 'latitude_x', 'longitude_x',
       #'akeed_order_id', 'payment_mode',
      # 'promo_code', 'vendor_discount_amount',
      # 'promo_code_discount_percentage', 'is_favorite', 'driver_rating', 'deliverydistance',
   #'preparationtime', 'created_at_x', 'LOCATION_NUMBER',
    #'LOCATION_TYPE', 'CID X LOC_NUM X VENDOR', 'authentication_id',
    #'latitude_y', 'longitude_y', 'vendor_category_en', 'vendor_category_id',
     #'delivery_charge', 'serving_distance', 'is_open', 'prepration_time',
    #'discount_percentage', 'status', 'verified_y',
    #'vendor_rating_y','primary_tags', 'vendor_tag_name', 'created_at_y', 'updated_at_y'],axis=1,inplace=True)

In [63]:
#df_final.to_csv('./data/Restaurant/df_final_dataset2.csv')